# docker-compose.yml
services:
  nginx:
    image: smoking_map-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - smoking-map-net
    restart: always

  backend:
    image: smoking_map-backend:latest
    container_name: backend-1
    ports:
      - "8080:8080"
    env_file: ./.env
    networks:
      - smoking-map-net

  frontend:
    image: smoking_map-frontend:latest
    build:
      context: ./smoking_map_frontend
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_NAVER_MAP_CLIENT_ID=rvkc2mgm2i
    container_name: frontend-1
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=https://smokingmap.duckdns.org:8080
      - NEXT_PUBLIC_NAVER_MAP_CLIENT_ID=rvkc2mgm2i
    depends_on:
      - backend
    networks:
      - smoking-map-net

networks:
  smoking-map-net:
    driver: bridge
