# naver api keys ??
naver:
  api:
    client-id: rvkc2mgm2i
    client-secret: gdn8hSuq1G1UzxOFlqH9qf1dSEqEJdBoweXudP23

spring:
  # ????? ??
  datasource:
    url: jdbc:mysql://smoking-map-db.cromckm028az.ap-northeast-2.rds.amazonaws.com:3306/smoking_map_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: noroot
    password: Gkstndi1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  # Spring Security OAuth2 (?? ???) ??
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 763582247348-0ee84nsvp99vdott2tqng1o23qo4m866.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

  # AWS ?? (spring ??? ???? ?)
  cloud:
    aws:
      credentials:
        access-key: AKIAUMYCITJJ3AJJ7YKM
        secret-key: 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
      region:
        static: ap-northeast-2
      s3:
        bucket: smoking-map-images-kknd03255
      stack:
        auto: false
  servlet:
    multipart:
      max-file-size: 10MB       # ?? ??? ?? ??? 10MB? ??
      max-request-size: 100MB   # ? ?? ??? ??? ?? ??? ? ??? 100MB? ??


# ?? ?? (spring? ??? ??)
server:
  servlet:
    session:
      tracking-modes: cookie
  tomcat:
    max-swallow-size: -1 # Tomcat? ??? ??? ??? ?? ??? ??

# ?? ?? ?? (spring? ??? ??)
logging:
  level:
    org.hibernate.SQL: debug

# 파일 맨 아래에 추가
admin:
  email: kknd03255@gmail.com # 이 부분을 ADMIN 권한을 가질 실제 구글 이메일로 변경하세요.