# nginx/Dockerfile.nginx
FROM nginx:latest

# Nginx 설정 파일을 이미지에 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Certbot 설정 파일들을 이미지에 복사
COPY options-ssl-nginx.conf /etc/letsencrypt/options-ssl-nginx.conf
COPY ssl-dhparams.pem /etc/letsencrypt/ssl-dhparams.pem
